name: 'Bikeclub Rides'
description: 'Provides Ride and Recurring ride content types.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
  - bikeclub_locations
install:
  # Core
  - content_moderation
  - workflows
  # Contrib.
  - calendar_view
  - datetime
  - datetimehideseconds
  - honeypot
  - smart_date
  - smart_date_recur
  - webform
  - webform_node
  - webform_options_limit
  - webform_templates
  - webform_ui
  - webform_views
  #Custom
  - bikeclub_ride_tools
config:
  strict: false
  import:
    smart_date: '*'
  actions:
    webform.settings:
      simpleConfigUpdate:
        default_submission_views:
          embed_administer:
            title: 'Administer submissions'
            view: 'webform_submissions_custom:embed_administer'
            global_routes:
              - entity.webform_submission.collection
            webform_routes: {  }
            node_routes: {  }
        default_submission_views_replace:
          global_routes:
            - entity.webform_submission.collection
            - entity.webform_submission.user
          webform_routes:
            - entity.webform.results_submissions
            - entity.webform.user.drafts
            - entity.webform.user.submissions
          node_routes:
            - entity.node.webform.results_submissions
            - entity.node.webform.user.drafts
            - entity.node.webform.user.submissions
        webform_submission_bulk_form: false
      user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create ride content'
        - 'create recurring_ride content'
        - 'delete any ride content'
        - 'delete any recurring_ride content'
        - 'edit any ride content'
        - 'edit any recurring_ride content'
        - 'use text format ride_page'
    user.role.rides_coordinator:
      createIfNotExists:
        label: 'Rides coordinator'
      grantPermissions:
        - 'create ride content'
        - 'create recurring_ride content'
        - 'delete any ride content'
        - 'delete any recurring_ride content'
        - 'edit any ride content'
        - 'edit any recurring_ride content'
        - 'use text format ride_page'